name: C/C++ CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  builds:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu:16.04', 'ubuntu:20.04', 'ubuntu:22.04' ]
    runs-on: ubuntu-latest
    container: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y \
            build-essential pkgconf \
            libevent-dev \
            libssl-dev \
            libpq-dev libsqlite3-dev \
            libhiredis-dev \
            libmongoc-dev \
            libmicrohttpd-dev
      # Different versions of ubuntu have different libmariadb packages
        apt-get install -y libmariadb-dev libmariadb-client-lgpl-dev || true
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: apps tests
      run: cd examples && ./run_tests.sh
